import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Contact',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>Contact page me apka swagat hai{children}</body>
    </html>
  )
}
